<a href="https://colab.research.google.com/github/Cris0402/Maria-Cristina-Betancur-Ramos/blob/main/Notebook_5_MARIA_CRISTINA_BETANCUR_RAMOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


#1.-Crear un arreglo de ceros de longitud 12

In [ ]:
#importa numpy
import numpy as np

arreglo_ejercicio_1 = np.zeros(12)
# Ver resultado
print(arreglo_ejercicio_1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**2.-Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5**


In [ ]:
#importa numpy
import numpy as np

arreglo_ejercicio_2 = np.zeros(10)
arreglo_ejercicio_2[4]=10
# Ver resultado
print(arreglo_ejercicio_2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


**3.-Crear un arreglo que tenga los números del 10 al 49**



In [ ]:
#importa numpy
import numpy as np

arreglo_ejercicio_3 = np.arange(10, 50, 1)

#Ver resultado
print(arreglo_ejercicio_3)

**4.-Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8**


In [1]:
#importa numpy
import numpy as np
import array

lista = [[0, 1, 2], [3, 4, 5],[6, 7, 8]]
arreglo_ejercicio_4 = np.array(lista)

#Ver resultado
print(arreglo_ejercicio_4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**5.-Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza**

In [6]:
#importa numpy
import numpy as np

arreglo_ejercicio_5 = np.random.randn(100)
media               = np.mean(arreglo_ejercicio_5)
varianza            = np.var(arreglo_ejercicio_5)
#Ver resultado
print("Media=", media, "Varianza=", varianza)


Media= -0.01732270987723985 Varianza= 1.041370652856453


**6.-Calcular la media de un arreglo usando np.sum**



In [8]:
#importa numpy
import numpy as np

arreglo_ejercicio_6 = np.arange(10, 50, 1)
ejercicio_6 = np.sum(arreglo_ejercicio_6)/len(arreglo_ejercicio_6)

#Ver resultado
print("Media=", ejercicio_6)

Media= 29.5


**7.-Calcular la varianza de un arreglo usando np.sum y np.mean**

In [9]:
#importa numpy
import numpy as np

arreglo_ejercicio_7 = np.arange(10, 50, 1)
ejercicio_7 = np.sum((abs(arreglo_ejercicio_7 - np.mean(arreglo_ejercicio_7))**2)/len(arreglo_ejercicio_7))

#Ver resultado
print("Varianza=",ejercicio_7)

Varianza= 133.25


**8.-Crear un array de números aleatorios usando np.random.randn.**

In [10]:
#importa numpy
import numpy as np

arreglo_ejercicio_8= np.random.rand(10)

#Ver resultado
print(arreglo_ejercicio_8)


[0.20958651 0.09732475 0.05438142 0.46521507 0.07629517 0.37083014
 0.53419897 0.03367138 0.78582475 0.64729687]
