<a href="https://colab.research.google.com/github/Cris0402/Maria-Cristina-Betancur-Ramos/blob/main/Notebook_5_MARIA_CRISTINA_BETANCUR_RAMOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


#1.-Crear un arreglo de ceros de longitud 12

In [8]:
#importa numpy
import numpy as np

arreglo_ejercicio_1 = np.zeros(12)
# Ver resultado
print(arreglo_ejercicio_1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**2.-Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5**


In [9]:
#importa numpy
import numpy as np

arreglo_ejercicio_2 = np.zeros(10)
arreglo_ejercicio_2[4]=10
# Ver resultado
print(arreglo_ejercicio_2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


3.-Crear un arreglo que tenga los números del 10 al 49



In [ ]:
#importa numpy
import numpy as np

arreglo_ejercicio_3 = np.arange(10, 50, 1)

#Ver resultado
print(arreglo_ejercicio_3)

4.-Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8


In [14]:
#importa numpy
import numpy as np
import array

lista = [[0, 1, 2], [3, 4, 5],[6, 7, 8]]
arreglo_ejercicio_4 = np.array(lista)

#Ver resultado
print(arreglo_ejercicio_4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:






#5.-Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
nuevo_array_5 = np.random.randn(100)
print(nuevo_array_5)
print(np.mean(nuevo_array_5))
print(np.var(nuevo_array_5))
#6.-Calcular la media de un arreglo usando np.sum
nuevo_array_6 = np.sum(nuevo_array_3)/len(nuevo_array_3)
print(nuevo_array_6)
#7.-Calcular la varianza de un arreglo usando np.sum y np.mean
nuevo_array_7 = np.sum((abs(nuevo_array_3 - np.mean(nuevo_array_3))**2)/len(nuevo_array_3))
print(nuevo_array_7)
#8.-Crear un array de números aleatorios usando np.random.randn
nuevo_array_8= np.random.rand(10)
print(nuevo_array_8)







